apiVersion: networking.k8s.io/v1
spec:
  rules:
  - host: argocd.dev.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: argocd-server
            port:
              name: http

kind: Ingress
metadata:
  name: argo-cd-ui