dex:
  enabled: false

server:
  extraArgs:
    - --insecure

configs:
  secret:
    createSecret: true
    argocdServerAdminPassword: "$2y$10$DulDL6kv6ABYwcz4SBxtiOevBjw7rdUgW6wBbmE3/RP6EvaAMBcde"
    