argocd_helm_charts_url: https://argoproj.github.io/argo-helm
argocd_default_namespace: argocd
argocd_default_admin_password: admin
argocd_default_ingress_enabled: False
argocd_default_insecure_state: True