- name: "Loading default values."
  include_tasks: load_default_vars.yml

- name: "Loading custom provided values."
  include_tasks: load_custom_vars.yml

- name: "Ensure host requirements are met."
  include_tasks: setup_host.yml
  when: (step_tracker == "preflight")