- name: "Loading nodes"
  include_tasks: load_vars.yml
  when: (step_tracker == "preflight")

- name: "Ensure host requirements are met."
  include_tasks: setup_host.yml
  when: (step_tracker == "preflight")