- name: Create/update RKE config file
  template:
    src: "templates/cluster.yml.j2"
    dest: "{{ workspace_directory }}/cluster.yml"
    mode: u=rw,g=r,o=
  register: rke_cluster_config

- name: Run RKE installer
  shell: rke up | tee {{ workspace_directory }}/rke-up.log
  args:
    chdir: "{{ workspace_directory }}/"

- name: Ensure the resulting kube_config_cluster.yml is present.
  stat:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
  register: kube_config_present

- name: Ensure the resulting kube_config_cluster.yml has the rights permissions.
  file:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
    mode: '0666'
  when: kube_config_present.stat.exists