- name: Check if the dummy files is older than the specified time.
  find:
    paths: '{{ stamped_file.path }}/'
    patterns: '.devopsed.stamp'
    age: '{{ stamped_file.older_than }}'
    file_type: file
    hidden: True
  register: reg_stamped_file_found

- name: Create/Overwrite the stamped if a match is found in the previous step.
  become: True
  copy:
    content: "devopd"
    dest: '{{ stamped_file.path }}/.devopsed.stamp'
    force: "{{ 'yes' if reg_stamped_file_found.matched > 0 else 'no' }}"
  register: reg_stamped_file_changed

  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#defining-different-values-for-true-false-null-ternary
- name: Export the stamped file 'changed' status
  set_fact:
    needs_update: "{{ reg_stamped_file_changed.changed | ternary(True, False, True) }}"