apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo-deployment
  labels:
    app: argo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-demo
  template:
    metadata:
      labels:
        app: argo-demo
    spec:
      containers:
        - name: argo-demo
          image: retersi/argo-demo:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: argo-demo-service
spec:
  selector:
    app: argo-demo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 8080