apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-creds
  namespace: shared-services
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:roman-hds/argo-demo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    .
    .
    .
    .
    -----END OPENSSH PRIVATE KEY-----  
  
    
    