# Provided keys.
- name: "Import the provided ssh keys currently inside the workspace directory if exists."
  file:
    src: "{{ workspace_directory }}"
    dest: "{{ '~/.ssh' | expanduser }}"
    state: link
    force: True

- name: Check if the ssh keys already exists
  stat:
    path: "{{ '~/.ssh' | expanduser }}/id_rsa"
  register: ssh_key_exists

# Newly generated keys
- name: "Generate an OpenSSH keypair with the default values (2048 bits, rsa)"
  community.crypto.openssh_keypair:
    path: "{{ '~/.ssh/id_rsa' | expanduser }}"
    size: 2048
  when: not ssh_key_exists.stat.exists