- name: Ensure config directory exists
  file:
    path: "{{ workspace_directory }}/cluster"
    state: directory
    recurse: True

- name: Create/update RKE config file
  template:
    src: "{{playbook_dir}}/rke/templates/cluster.yml.j2"
    dest: "{{ workspace_directory }}/cluster/cluster.yml"
    mode: u=rw,g=r,o=
  register: rke_cluster_config
  when: |-
    "rke" in triggers|default([])

- name: Run RKE installer
  shell: |
    rke up | tee "{{ workspace_directory }}/rke-up.log"
  args:
    chdir: "{{ workspace_directory }}/cluster"
  when: |-
    "install" in triggers|default([]) and
    "rke" in triggers|default([])

- name: Uninstall RKE from nodes.
  shell: |
    rke remove --force | tee "{{ workspace_directory }}/rke-up.log"
  args:
    chdir: "{{ workspace_directory }}/cluster"
  when: |-
    "remove" in triggers|default([]) and
    "rke" in triggers|default([])