- name: "Encrypt the admin password."
  encrypt_string:
    clear_string: "{{ cluster.addons.argocd.admin_password | default(argocd_default_admin_password) }}"
    encryption: "bcrypt"
  register: reg_encrypted_admin_password
  notify: export encrypted values

- name: "Set ArgoCD variables."
  set_fact:
    argocd_cluster_url: "https://argocd-{{cluster.environment}}.{{cluster.domain}}"
    argocd_cluster_name: "argocd-{{cluster.environment}}.{{cluster.domain}}"
    encrypted_admin_password: "{{ reg_encrypted_admin_password.stdout | trim }}"
  notify: export encrypted values

- name: "Generate cluster encrypted values."
  set_fact:
    encrypted_argocd_config: "{{ lookup('template', 'templates/argocd.cluster.config.json.j2') | to_json | b64encode }}"
    encrypted_argocd_name: "{{ argocd_cluster_name | b64encode }}"
    encrypted_argocd_server: "{{ argocd_cluster_url | b64encode }}"
  notify: export encrypted values