- name: "Deploy Sealed secrets into the cluster."
  include_tasks: sealed_secrets.yml
  when: (cluster.addons.sealed_secrets.enabled | default(False) | bool) or
        (step | default("deploy") == "deploy")

- name: "Short break before deploying the WebGUI."
  pause:
    seconds: 5

- name: "Deploy Sealed secrets WebGUI into the cluster."
  include_tasks: sealed_secrets_webgui.yml
  when: ((cluster.addons.sealed_secrets.enabled | default(False) | bool) and
        (cluster.addons.sealed_secrets.enable_webgui | default(False) | bool)) or
        (step | default("deploy") == "deploy")