- name: Check if a values files is provided for argocd.
  stat:
    path: "{{ workspace_directory }}/argocd-values.yaml"
  register: argocd_custom_values

- name: Add ArgoCD helm repository.
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "{{ argocd_helm_charts_url }}"

- name: "Deploy ArgoCD."
  kubernetes.core.helm:
    name: argo
    chart_ref: argo/argo-cd
    release_namespace: "{{ cluster.addons.argocd.namespace | default('argocd') }}"
    create_namespace: True
    kubeconfig: "{{ workspace_directory }}/kube_config_cluster.yml"
    values_files: 
      - '{{ value_file | trim }}'
      
