- name: Confirm that the kubeconfig file is exists
  stat:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
  register: kubeconfig_exists

- name: "Fail if the kubeconfig doesnt exists since its a dependency."
  fail:
    msg: "Cant find the kubeconfig file."
  when: not kubeconfig_exists.stat.exists

- name: Ensure the Sealed secrets output directory exists before exporting keys.
  file:
    path: "{{ workspace_directory }}/sealed_keys"
    state: directory

- name: "Fetch Sealed secrets controller private key."
  environment:
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
  shell: |
    kubectl \
    --kubeconfig {{ workspace_directory }}/kube_config_cluster.yml get secret \ 
    --namespace {{ cluster.addons.sealed_secrets.namespace }} \
    -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > {{ workspace_directory }}/sealed_keys/ss-private-key.yaml
  when: (step == "private")

- name: Read the generated Sealed secrets PRIVATE key (if verbose).
  debug:
    msg: "{{ lookup('file', workspace_directory + '/sealed_keys/ss-private-key.yaml') | from_yaml }}"
  when: (verbose_exec|default(False)|bool == True) and
        (step == "private")

- name: "Fetch Sealed secrets controller public key."
  environment:
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
  shell: |
    kubeseal \
    --kubeconfig {{ workspace_directory }}/kube_config_cluster.yml \
    --controller-name sealed-secrets \
    --controller-namespace {{ cluster.addons.sealed_secrets.namespace }} \
    --fetch-cert > {{ workspace_directory }}/sealed_keys/ss-public-key.pem
  when: (step == "public")

- name: Read the generated Sealed secrets PUBLIC key (if verbose).
  debug:
    msg: "{{ lookup('file', workspace_directory + '/sealed_keys/ss-public-key.pem') | from_yaml | indent( width=4, first=True) }}"
  when: (verbose_exec|default(False)|bool == True) and
        (step == "public")
