- name: Confirm that the kubeconfig file is exists
  stat:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
  register: kubeconfig_exists

- name: "Fail if the kubeconfig doesnt exists since its a dependency."
  fail:
    msg: "Cant find the kubeconfig file."
  when: not kubeconfig_exists.stat.exists

- name: Ensure the Sealed secrets output directory exists before exporting keys.
  file:
    path: "{{ workspace_directory }}/sealed_keys/"
    state: directory

- name: "Fetch Sealed secrets controller private key."
  environment:
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
  shell: |
    kubectl --kubeconfig {{ workspace_directory }}/kube_config_cluster.yml get secret \ 
    --namespace {{ cluster.addons.sealed_secrets.namespace }} \
    -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > {{ workspace_directory }}/sealed_keys/ss-private-key.yaml
  when: (step == "private")

- name: "Fetch Sealed secrets controller public key."
  environment:
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
  shell: |
    kubeseal \
    --kubeconfig {{ workspace_directory }}/kube_config_cluster.yml \
    --controller-name sealed-secrets-controller \
    --controller-namespace {{ cluster.addons.sealed_secrets.namespace }} \
    --fetch-cert > {{ workspace_directory }}/sealed_keys/ss-public-key.yaml
  when: (step == "public")
