- name: Confirm that the kubeconfig file is exists
  stat:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
  register: kubeconfig_exists

- name: "Confirm that the Sealed secrets controller public key exists at : {{ workspace_directory }}/ss-public.pem"
  stat:
    path: "{{ workspace_directory }}/ss-public.pem"
  register: publickey_exists

- name: Fail if the kubeconfig doesnt exists since its a dependency.
  fail:
    msg: "Cant find the kubeconfig file."
  when: not kubeconfig_exists.stat.exists

- name: Fail if the Sealed secrets controller public key doesnt exists.
  fail:
    msg: "Cant find the Sealed secrets public key at : {{ workspace_directory }}/ss-public.pem"
  when: not publickey_exists.stat.exists

- name: Add Sealed secrets WebGUI helm repository.
  kubernetes.core.helm_repository:
    name: kubesealwebgui
    repo_url: "{{ sealed_secrets_webgui.helm_charts_url }}"

- name: "Fetch the Sealed secrets public key."
  set_fact:
    ss_public_key: "{{ lookup('file', workspace_directory + '/ss-public.pem') }}"

- debug:
    msg: "{{ss_public_key}}"

- name: "Deploy Sealed secrets WebGUI into the cluster."
  kubernetes.core.helm:
    atomic: True
    name: kubesealwebgui
    chart_ref: kubesealwebgui/kubeseal-webgui
    release_namespace: "{{ cluster.addons.sealed_secrets.namespace | default('kube-system') }}"
    create_namespace: True
    kubeconfig: "{{ workspace_directory }}/kube_config_cluster.yml"
    values:
      replicaCount: 1
      annotations: {}
      api:
        url: "https://kubeseal-{{ cluster.environment }}.{{ cluster.domain }}"
        image:
          repository: kubesealwebgui/api
          tag: "{{ sealed_secrets_webgui.version | default('latest') }}"
        environment: {}
      ui:
        image:
          repository: kubesealwebgui/ui
          tag: "{{ sealed_secrets_webgui.version | default('latest') }}"
      image:
        pullPolicy: Always

      serviceaccount:
        create: true

      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 20m
          memory: 256Mi

      sealedSecrets:
        autoFetchCert: false
        controllerName: sealed-secrets-controller
        controllerNamespace: "{{ cluster.addons.sealed_secrets.namespace | default('kube-system') }}"
        cert: |
          {{ ss_public_key }}
          