- name: Confirm that the kubeconfig file is exists
  stat:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
  register: kubeconfig_exists

- name: Fail if the kubeconfig doesnt exists since its a dependency.
  fail:
    msg: "Cant find the kubeconfig file."
  when: not kubeconfig_exists.stat.exists

- name: Add Sealed secrets helm repository.
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: "{{ sealed_secrets.helm_charts_url }}"

- name: "Deploy Sealed Secrets operator."
  kubernetes.core.helm:
    atomic: True
    name: sealed-secrets-controller
    chart_ref: sealed-secrets/sealed-secrets
    wait: True
    create_namespace: True
    release_namespace: "{{ cluster.addons.sealed_secrets.namespace }}"
    release_state: present
    release_values:
      fullnameOverride: sealed-secrets-controller

- name: "Export the Sealed secrets controller public key."
  environment: 
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
  shell:
    kubectl get secret --field-selector type=kubernetes.io/tls -o=jsonpath="{.items[*].data.tls\.crt}" -n {{ cluster.addons.sealed_secrets.namespace }} | base64 -d > {{ workspace_directory }}/ss-public.pem