- name: Add Sealed secrets helm repository.
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: "{{ sealed_secrets_helm_charts_url }}"

- name: "Deploy Sealed Secrets operator."
  kubernetes.core.helm:
    atomic: True
    name: sealed-secrets
    chart_ref: sealed-secrets/sealed-secrets
    release_namespace: "{{ cluster.addons.sealed_secrets.namespace | default('shared-services') }}"
    create_namespace: True
    kubeconfig: "{{ workspace_directory }}/kube_config_cluster.yml"
