- name: Confirm that the kubeconfig file is exists
  stat:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
  register: kubeconfig_exists

- name: Fail if the kubeconfig doesnt exists since its a dependency.
  fail:
    msg: "Cant find the kubeconfig file."
  when: not kubeconfig_exists.stat.exists

- name: Add Sealed secrets helm repository.
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: "{{ sealed_secrets_helm_charts_url }}"

- name: "Deploy Sealed Secrets operator."
  kubernetes.core.helm:
    atomic: True
    name: sealed-secrets
    chart_ref: sealed-secrets/sealed-secrets
    wait: True
    wait_timeout: '120s'
    kubeconfig: "{{ workspace_directory }}/kube_config_cluster.yml"
    release_state: present
    release_namespace: "{{ cluster.addons.sealed_secrets.namespace | default(sealed_secrets_default_namespace) }}"
    create_namespace: True
    values:
      namespace: "{{ cluster.addons.sealed_secrets.namespace | default(sealed_secrets_default_namespace) }}"
