- name: "Export credentials manifests in the logs directory (if verbose)."
  template:
    src: templates/repository.credential.yml.j2
    dest: "{{ workspace_directory }}/logs/repo.creds-{{ repo_credential.name }}.yml"
    force: True
  vars:
    creds:
      name: "{{ repo_credential.name | default('undefined') }}"
      repo_url: "{{ repo_credential.repo_url | default('undefined') }}"
      repo_username: "{{ repo_credential.repo_username | default('undefined') }}"
      repo_password: "{{ repo_credential.repo_password | default('undefined') }}"
      repo_ssh_key: "{{ repo_credential.repo_ssh_key | default('undefined') }}"
  with_items: "{{ repositories_creds | default([]) }}"
  loop_control:
    loop_var: repo_credential
  when: (verbose_exec | default(False) | bool)
  listen: export repocreds manifests

- name: "Export the ArgoCD cluster manifest (if verbose)."
  template:
    src: templates/argocd.cluster.yml.j2
    dest: "{{ workspace_directory }}/logs/argocd.cluster.yml"
    force: True
  when: (verbose_exec | default(False) | bool)
  listen: export cluster manifests

- name: "Print the generated encrypted cluster manifests."
  debug:
    msg: "{{ lookup('template', 'templates/argocd.cluster.yml.j2') | from_yaml }}"
  when: (verbose_exec | default(False) | bool)
  listen: export cluster manifests

- name: "Print generated values (if verbose)."
  debug:
    msg:
      - "{{ argocd_cluster_url | default('ERROR') }}"
      - "{{ argocd_cluster_name | default('ERROR') }}"
      - "{{ encrypted_admin_password | default('ERROR') }}"
      - "{{ encrypted_argocd_config | default('ERROR') }}"
      - "{{ encrypted_argocd_name | default('ERROR') }}"
      - "{{ encrypted_argocd_server | default('ERROR') }}"
  when: (verbose_exec | default(False) | bool)
  listen: export encrypted values