- name: Check if a values files is provided for argocd.
  stat:
    path: "{{ workspace_directory }}/values.yaml"
  register: argocd_custom_values

- name: Add ArgoCD helm repository.
  kubernetes.core.helm_repository:
    name: argo-cd
    repo_url: https://argoproj.github.io/argo-helm

- name: Set values to use in the deployment.
  set_fact:
    value_file: >-
      {% set out = "{{role_path}}/files/default-values.yml" %}
      {% if argocd_custom_values.stat.exists == True %}
      {% set out = "{{workspace_directory}}/values.yml" %}
      {% endif %}
      {{ out }}

- debug:
    msg: "{{ value_file }}"

- meta: end_play

- name: "Deploy ArgoCD {{ cluster.addons.argocd.version | default('4.6.0') }}"
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo-cd
    namespace: "{{ cluster.addons.argocd.namespace | default('argocd') }}"
    create_namespace: True
    chart_version: "{{ cluster.addons.argocd.version | default('4.6.0') }}"
    update_repo_cache: true
    kubeconfig: "{{ workspace_directory }}/kube_config_cluster.yml"
    values_files: >-
      {% set out = role_path + "/files/default-values.yml" %}
      {% if argocd_custom_values.stat.exists == True %}
      {% set out = "{{workspace_directory}}/values.yml" %}
      {% endif %}
      {{ out }}
      
