cluster:
  name: 'cluster-qa'
  environment: 'qa'
  domain: organization.com
  user: 'sudo-user'
  password: 'sudo-user-password'
  nodes:
    - address: 10.10.10.11
      hostname: rkeqa-master-0
    - address: 10.10.10.12
      hostname: rkeqa-master-1
    - address: 10.10.10.13
      hostname: rkeqa-master-2
    - address: 10.10.10.14
      hostname: rkeqa-worker-0
    - address: 10.10.10.15
      hostname: rkeqa-worker-1
    - address: 10.10.10.16
      hostname: rkeqa-worker-2

  ingress:
    enabled: false
    controller: nginx
    network_mode: hostPort

  addons:
    etcd_snapshots:
      enabled: false
      creation: '12h'
      retention: '24h'
    argocd:
      enabled: true
      ingress: false
      insecure: true
      namespace: argocd
      admin_password: admin

      cluster:
        local: true
        server: 'https://kubernetes.default.svc'

repositories_creds:
    # Secret name
  - name: repocred-bitbucket-example
    # Repositories base url.
    repo_url: https://bitbucket.org/organizationinc
    # Login username.
    repo_username: username
    # AppAuth Token
    repo_password: password

    # Secret name
  - name: repocred-azure-example
    # Repositories base url.
    repo_url: https://organization@dev.azure.com/organization/
    # Login username.
    repo_username: 0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0aa0a0
    # AppAuth Token
    repo_password: 0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0aa0a0
