- hosts: localhost
  gather_facts: True
  tasks:
  - set_fact: { step_tracker: 'preflight' }
  - include_role: { name: kubernetes }

- hosts: lst_nodes
  gather_facts: True
  tasks:
  - set_fact: { step_tracker: 'nodesprereq' }
  - include_role: { name: kubernetes }

- hosts: localhost
  gather_facts: True
  tasks:
  - set_fact: { step_tracker: 'kubernetes' }
  - include_role: { name: kubernetes }

  - set_fact: { step_tracker: 'argocd' }
  #- include_role: { name: argocd } 
  #  when: (mode_exec == 'install') and
  #        (cluster.addons.argocd.enabled | default(False) | bool) == True