- hosts: localhost
  gather_facts: True
  tasks:
  - name: "Set global facts from provided triggers list."
    set_fact:
      mode_exec: '{{ "remove" if "remove" in triggers else "install" }}'
      verbose_exec: "{{ True if 'verbose' in triggers else False }}"
      workspace_directory: "{{ ansible_env.HOME | default('/root') }}/rke"
#     argocd_cluster_url: "https://argocd-{{cluster.environment}}.{{cluster.domain}}"
#     argocd_cluster_name: "argocd-{{cluster.environment}}.{{cluster.domain}}"

  - name: "Generate hosts list from the provided config.yml file."
    add_host:
      hostname: '{{item.address|trim|ansible.netcommon.ipaddr}}'
      ansible_connection: ssh
      ansible_user: "{{cluster.user|trim}}"
      ansible_ssh_pass: "{{cluster.password|trim}}"
      ansible_become_pass: "{{cluster.password|trim}}"
      groups: lst_nodes
    with_items: "{{cluster.nodes|default([])}}"

  - name: Run host prerequisites
    include_role: 
      name: rke
    vars:
      step: host

- hosts: lst_nodes
  gather_facts: True
  tasks:
  - name: "Install prerequisites on all nodes."
    include_role: 
      name: rke
    vars:
      step: nodes

- hosts: localhost
  gather_facts: True
  tasks:
  - name: "Run Kubernetes RKE binary in the specified mode."
    include_role: 
      name: rke
    vars:
      step: "rke"

  - name: "Deploy Sealed Secrets."
    include_role: 
      name: sealed-secrets
    when: ("install" in triggers) and
          ("argocd" in triggers) or
          ("op-sealed-secrets" in triggers)

  - name: "Deploy ArgoCD."
    include_role: 
      name: argocd
    vars:
      step: deploy
    when: ("install" in triggers) and
          ("argocd" in triggers)

  - name: "Create the ArgoCD cluster."
    include_role: 
      name: argocd
    vars:
      step: cluster
    when: ("install" in triggers) and
          ("argocd" in triggers)
          