- hosts: localhost
  gather_facts: True
  tasks:
  - name: "Generate hosts list from the provided config.yml file."
    add_host:
      hostname: '{{item.address|trim|ansible.netcommon.ipaddr}}'
      ansible_connection: ssh
      ansible_user: "{{cluster.user|trim}}"
      ansible_ssh_pass: "{{cluster.password|trim}}"
      ansible_become_pass: "{{cluster.password|trim}}"
      groups: lst_nodes
    with_items: "{{cluster.nodes|default([])}}"

  - name: Run host prerequisites
    include_role: 
      name: rke
    vars:
      step: host

- hosts: lst_nodes
  gather_facts: True
  tasks:
  - name: "Install prerequisites on all nodes."
    include_role: 
      name: rke
    vars:
      step: nodes

- hosts: localhost
  gather_facts: True
  tasks:
  - name: "Set execution mode before we start."
    set_fact:
      exec_mode: |-
        {% set mode = '' %}
        {% if "rke" in triggers and "install" in triggers %}
        {% set mode = 'up' %}
        {% elif "argocd" in triggers and "install" in triggers %}
        {% set mode = 'up' %}
        {% elif "remove" in triggers %}
        {% set mode = 'remove' %}
        {% endif %}
        {{ mode }}

  - name: "Run Kubernetes RKE binary in the specified mode."
    include_role: 
      name: rke
    vars:
      step: "rke-{{exec_mode}}"
    when: exec_mode != ''

  - name: "Deploy Sealed Secrets operator."
    include_role: 
      name: sealed-secrets
    vars:
      step: deploy
    when: ("install" in triggers) and
          ("argocd" in triggers) or 
          ("op-sealed-secrets" in triggers)

  - name: "Deploy ArgoCD."
    include_role: 
      name: argocd
    vars:
      step: deploy
    when: ("install" in triggers|default([])) and
          ("argocd" in triggers|default([])) 
          