cluster:
  domain: local.local
  environment: dev
  user: admin
  password: admin

  nodes:
    - address: 10.0.0.175
      hostname: node1
    - address: 10.0.0.176
      hostname: node2
    - address: 10.0.0.177
      hostname: node3

  addons:
    etcd_snapshots:
      enabled: True

    argocd:
      enabled: False
      flavor: vanilla

networking:
  # Default: calico
  enable_default: True
  # The custom network cni to use in case enable_default is False
  custom_network_cni: cilium

ingress:
  # Default: nginx
  enable_default: True
  # The custom ingress controller to use in case enable_default is False
  custom_ingress_controller: nginx

# Could be /var/run/docker.sock too.
docker_socket_path: /var/run/docker.sock

workspace_directory: "{{ ansible_env.HOME | default(ansible_env.PWD) | default('/root') }}/rke"