cluster:
  domain: local.local
  environment: dev
  user: admin
  password: admin

  nodes:
    - address: 10.0.0.175
      hostname: cluster

  addons:
    etcd_snapshots:
      enabled: True

    argocd:
      enabled: False
      flavor: vanilla