- name: "Deploy ArgoCD."
  shell: |
    /bin/argocd-autopilot repo bootstrap \
    --installation-mode 'flat' \
    --context {{ kubernetes_cluster_name }} \
    --hide-password \ 
    {{ '--insecure' if (cluster.addons.argocd.secure | default(false) | bool) == True else None }} \
    {{ '--upsert-branch' if (cluster.addons.argocd.bootstrap.git_repo_branch != 'undefined' and cluster.addons.argocd.bootstrap.git_repo_branch != '') else None }}
  environment: 
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
    GIT_TOKEN: "{{ cluster.addons.argocd.bootstrap.git_token }}"
    GIT_USER: "{{ cluster.addons.argocd.bootstrap.git_user | default(omit) }}"
    GIT_REPO: |-
      {{ cluster.addons.argocd.bootstrap.git_repo }}{{ '?ref=' + cluster.addons.argocd.bootstrap.git_repo_branch if (cluster.addons.argocd.bootstrap.git_repo_branch != 'undefined' and cluster.addons.argocd.bootstrap.git_repo_branch != '') else None }}

- name: "Set ArgoCD custom admin password."
  shell: |
    /bin/kubectl -n {{ argocd_namespace }} patch secret argocd-secret -p \
      '{
        "stringData": {
          "admin.password": "{{ argocd_encrypted_admin_password }}",
          "admin.passwordMtime": "'$(date +%FT%T%Z)'"
        }
      }'
  environment: 
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
    GIT_TOKEN: "{{ cluster.addons.argocd.bootstrap.git_token }}"
    GIT_REPO: "{{ cluster.addons.argocd.bootstrap.git_repo }}"