- name: "Ensure the ArgoCD cluster is created."
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    definition: "{{ lookup('template', 'templates/argocd.cluster.yml.j2') | from_yaml }}"
    kubeconfig: "{{ workspace_directory }}/kube_config_cluster.yml"
  notify: export cluster manifests