- name: Confirm that the kubeconfig file is exists
  stat:
    path: "{{ workspace_directory }}/kube_config_cluster.yml"
  register: kubeconfig_exists

- name: Fail if the kubeconfig doesnt exists since its a dependency.
  fail:
    msg: "Cant find the kubeconfig file."
  when: not kubeconfig_exists.stat.exists

- name: Check if a values files is provided for argocd.
  stat:
    path: "{{ workspace_directory }}/values.yaml"
  register: argocd_custom_values

- name: Add ArgoCD helm repository.
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "{{ cluster.addons.argocd.helm_charts_url }}"

- name: "Deploy ArgoCD."
  kubernetes.core.helm:
    atomic: True
    name: argo
    wait: True
    chart_ref: argo/argo-cd
    release_namespace: "{{ cluster.addons.argocd.namespace }}"
    create_namespace: True
    kubeconfig: "{{ workspace_directory }}/kube_config_cluster.yml"
    values:
      namespace: "{{ cluster.addons.argocd.namespace }}"
      dex:
        enabled: false

      server:
        extraArgs:
          - --insecure

      configs:
        secret:
          createSecret: true
          argocdServerAdminPassword: "{{ cluster.addons.argocd.installation.admin_default_password }}"
      
