- name: "Deploy ArgoCD."
  shell: |
    argocd-autopilot repo bootstrap --repo {{ cluster.addons.argocd.bootstrap.repo_url }} --installation-mode flat
  environment: 
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
    GIT_TOKEN: "{{ cluster.addons.argocd.bootstrap.git_token }}"
    GIT_REPO: "{{ cluster.addons.argocd.bootstrap.git_repo }}"
    GIT_USER: "{{ cluster.addons.argocd.bootstrap.git_user | default(omit) }}"

- name: "Set ArgoCD custom admin password."
  shell: |
    /bin/kubectl -n {{ argocd_namespace }} patch secret argocd-secret -p \
      '{
        "stringData": {
          "admin.password": "{{ argocd_encrypted_admin_password }}",
          "admin.passwordMtime": "'$(date +%FT%T%Z)'"
        }
      }'
  environment: 
    KUBECONFIG: "{{ workspace_directory }}/kube_config_cluster.yml"
    GIT_TOKEN: "{{ cluster.addons.argocd.bootstrap.git_token }}"
    GIT_REPO: "{{ cluster.addons.argocd.bootstrap.git_repo }}"