# step: deploy
- name: "Deploy ArgoCD if conditions are met."
  include_tasks: argocd_server.yml
  when: (cluster.addons.argocd.enabled | default(False) | bool) and
        (step == "deploy")

# step: repocreds
- name: "Generate ArgoCD repository credentials."
  include_tasks: argocd_repo_creds.yml
  when: (cluster.addons.argocd.enabled | default(False) | bool) and
        (argocd.repo_credentials_templates | default([]) | length) > 0 and
        (step == "repocreds")