# step: deploy argocd (Helm version)
- name: "Install ArgoCD base (Helm version)."
  include_tasks: argocd_server.yml
  when: (cluster.addons.argocd.bootstrap.enabled | default(false) | bool) == false

# step: deploy argocd (ArgoCD-Autopilot)
- name: "Install ArgoCD base (ArgoCD-Autopilot)."
  include_tasks: argocd_autopilot.yml
  when: (cluster.addons.argocd.bootstrap.enabled | default(false) | bool) == true

# step: generate and apply argocd cluster manifest.
- name: "Deploy ArgoCD cluster."
  include_tasks: argocd_cluster.yml
  when: (cluster.addons.argocd.cluster.create| default(false) | bool) == true

# step: generate and apply argocd repositories credentials.
- name: "Generate ArgoCD repository credentials."
  include_tasks: argocd_repo_creds.yml