- name: Ensure the logs directory exists.
  file:
    path: "{{ workspace_directory }}/logs"
    state: directory
  when: (verbose_exec | default(False) | bool)

# loading encrypted variables.
- name: "Loading encrypted vars."
  include_tasks: load_vars.yml
  when: (cluster.addons.argocd.enabled | default(False) | bool)

# step: deploy
- name: "Deploy ArgoCD if conditions are met."
  include_tasks: argocd_server.yml
  when: (cluster.addons.argocd.enabled | default(False) | bool) and
        (step == "deploy")

# step: cluster
- name: "Deploy and ArgoCD cluster."
  include_tasks: argocd_cluster.yml
  when: (cluster.addons.argocd.enabled | default(False) | bool) and
        (step == "cluster")  

# step: repocreds
- name: "Generate ArgoCD repository credentials."
  include_tasks: argocd_repo_creds.yml
  when: (cluster.addons.argocd.enabled | default(False) | bool) and
        (repositories_creds | default([]) | length) > 0 and
        (step == "repocreds")