cluster:
  domain: local.local
  environment: dev
  user: admin
  password: admin

  nodes:
    - address: 10.0.0.175
      hostname: node1
    - address: 10.0.0.176
      hostname: node2
    - address: 10.0.0.177
      hostname: node3

  addons:
    etcd_snapshots:
      enabled: True