cluster:
  # Organization domain.
  domain: local.local
  # Cluster environment.
  environment: dev
  # Nodes sudo username.
  user: admin
  # Nodes sudo user password.
  password: admin

  # List of nodes composing the cluster.
  nodes:
    - address: 10.0.0.175
      hostname: node1
    - address: 10.0.0.176
      hostname: node2
    - address: 10.0.0.177
      hostname: node3

  # List of services / addons to enable.
  addons:
    # Etcd automatics snapshots.
    etcd_snapshots:
      # Enable Etcd snapshots.
      enabled: True
      # Snapshots creation interval.
      creation: 12h
      # Time retentions of each snapshots taken.
      retention: 24h

    # ArgoCD Gitops engine.
    argocd:
      # Enable ArgoCD
      enabled: True
      # ArgoCD version to deploy.
      version: 4.5.12
      # Namespace to deploy ArgoCD to.
      namespace: 'argocd'

    # Sealed secrets controller and webgui.
    sealed_secrets:
      # Enable sealed secrets controller.
      enabled: True
      # Enable sealed secrets webgui.
      enable_webgui: True
      # Sealed secrets version to deploy.
      version: 1.16.1
      # Namespace to deploy Sealed secrets controller / webgui to.
      namespace: 'kube-system'

# Cluster networking configuration.
networking:
  # Default: calico
  enable_default: True
  # The custom network cni to use in case enable_default is False
  custom_network_cni: cilium

# Ingress controller configuration.
ingress:
  # Default: nginx
  enable_default: True
  # The custom ingress controller to use in case enable_default is False
  custom_ingress_controller: nginx

# Could be /var/run/docker.sock too.
docker_socket_path: /var/run/docker.sock

workspace_directory: "{{ ansible_env.HOME | default(ansible_env.PWD) | default('/root') }}/rke"